# 1. 假设有一个数组，第i个元素是一支给定的股票在第i天的价格。如果你最多只允许完成一次交易（例如一次买卖股票），请找出最大利润。

In [29]:
import copy
import numpy as np
stock=[1,2,3,9,2,1]
n=len(stock)
buy=copy.copy(stock)
sale=copy.copy(stock)
profit=np.zeros((n,n))
for i in range(n):
    for j in range(i,n):
        profit[i][j]=sale[j]-buy[i]
        j+=1
    i+=1
print(profit,"The maximum profit you can gain is:", profit.max())
for i in range(n):
    for j in range(i,n):
        if profit[i][j]==profit.max():
            print("you should buy in", i+1,"day and sale the stock in",j+1, "day.")

[[ 0.  1.  2.  8.  1.  0.]
 [ 0.  0.  1.  7.  0. -1.]
 [ 0.  0.  0.  6. -1. -2.]
 [ 0.  0.  0.  0. -7. -8.]
 [ 0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.]] The maximum profit you can gain is: 8.0
you should buy in 1 day and sale the stock in 4 day.


# 2. 基于1，保证用户怎么都不会亏钱

In [25]:
import copy
import numpy as np
stock=[1,2,3,9,2,1]
#stock=[2,1,1]
n=len(stock)
buy=copy.copy(stock)
sale=copy.copy(stock)
profit=np.zeros((n,n))
for i in range(n):
    for j in range(i,n):
        profit[i][j]=sale[j]-buy[i]
        j+=1
    i+=1
for i in range(n):
    for j in range(i,n):
        if profit[i][j]>0:
            print("you can buy in", i+1,"day and sale the stock in",j+1, "day to gain",profit[i][j],"profit.")
if profit.max()<0 or profit.max()==0:
    print("you should not buy in the next", n,"days.")
else:
    print("The maximum profit you can gain is:", profit.max())

you can buy in 1 day and sale the stock in 2 day to gain 1.0 profit.
you can buy in 1 day and sale the stock in 3 day to gain 2.0 profit.
you can buy in 1 day and sale the stock in 4 day to gain 8.0 profit.
you can buy in 1 day and sale the stock in 5 day to gain 1.0 profit.
you can buy in 2 day and sale the stock in 3 day to gain 1.0 profit.
you can buy in 2 day and sale the stock in 4 day to gain 7.0 profit.
you can buy in 3 day and sale the stock in 4 day to gain 6.0 profit.
The maximum profit you can gain is: 8.0
