# 寻找距离其他点最大的点

In [1]:
import numpy as np
a=[-1,3,6,9,0]
n=len(a)
distance=np.zeros((n,n))
diatance_sum=np.zeros((n,1))
for i in range(n):
    for j in range(n):
        distance[i][j]=abs(a[i]-a[j])
distance_sum=distance.sum(axis=1)
for i in range(0,n):
    if distance_sum[i]==distance_sum.max():
        print(distance,distance_sum,"target point is:",a[i])       
        

[[ 0.  4.  7. 10.  1.]
 [ 4.  0.  3.  6.  3.]
 [ 7.  3.  0.  3.  6.]
 [10.  6.  3.  0.  9.]
 [ 1.  3.  6.  9.  0.]] [22. 16. 19. 28. 19.] target point is: 9
